[package]
name = "mapreduce"
version = "0.1.0"
authors = ["Raghav Kuppan <raghav.kuppan@gatech.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
